const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

async function main() {
    const advertisers = await prisma.advertiser.createMany({

        data: [{
            name: 'Great Ads',
            type: 'agency',
            email: 'info@greatads.com',
            phone: '123-456-7890',
            address: '123 Main St, Anytown, USA',
            creditLimit: 1000000,
            term: 'net 30'
        },
        {
            name: 'Grupo MK',
            type: 'agency',
            email: 'info@grupomk.com',
            phone: '123-456-7890',
            address: '123 Main St, Anytown, USA',
            creditLimit: 1000000,
            term: 'net 60'
        },
        {
            name: 'Ninja View',
            type: 'agency',
            email: 'info@ninjaview.com',
            phone: '123-456-7891',
            address: '124 Main St, Anytown, USA',
            creditLimit: 2000000,
            term: 'prepaid'
        },
        {
            name: 'Great Story',
            type: 'agency',
            email: 'info@greatstory.com',
            phone: '123-456-7892',
            address: '125 Main St, Anytown, USA',
            creditLimit: 3000000,
            term: 'net 30'
        },
        {
            name: 'Hill St LTD',
            type: 'agency',
            email: 'info@hillstltd.com',
            phone: '123-456-7893',
            address: '126 Main St, Anytown, USA',
            creditLimit: 4000000,
            term: 'net 30'
        },
        {
            name: 'DSA Adv',
            type: 'agency',
            email: 'info@dsaadv.com',
            phone: '123-456-7894',
            address: '127 Main St, Anytown, USA',
            creditLimit: 5000000,
            term: 'net 30'
        },
        {
            name: 'Others Inc',
            type: 'agency',
            email: 'info@othersinc.com',
            phone: '123-456-7895',
            address: '128 Main St, Anytown, USA',
            creditLimit: 6000000,
            term: 'net 30'
        },
        {
            name: 'Finally GA',
            type: 'agency',
            email: 'info@finallyga.com',
            phone: '123-456-7896',
            address: '129 Main St, Anytown, USA',
            creditLimit: 7000000,
            term: 'net 30'
        },
        {
            name: 'EP Inc',
            type: 'agency',
            email: 'info@epinc.com',
            phone: '123-456-7897',
            address: '130 Main St, Anytown, USA',
            creditLimit: 8000000,
            term: 'net 30'
        },
        {
            name: 'Kualus',
            type: 'agency',
            email: 'info@kualus.com',
            phone: '123-456-7898',
            address: '131 Main St, Anytown, USA',
            creditLimit: 9000000,
            term: 'net 30'
        }
        ]
    })

    const campaigns = await prisma.campaign.createMany({
        data: [{
            advertiserId: 1,
            name: 'Premium Zone',
            brand: 'Iphone 15',
            maxBid: 0.05,
            budget: 1000,
            status: 'active',
            startDate: new Date('2021-01-01'),
            endDate: new Date('2024-12-31'),
        },
        {
            advertiserId: 1,
            name: 'Medium Zone',
            brand: 'Samsung Galaxy 20',
            maxBid: 0.03,
            budget: 500,
            startDate: new Date('2021-01-01'),
            endDate: new Date('2024-05-01'),
            status: 'expired',
        },
        {
            advertiserId: 1,
            name: 'Low Zone',
            brand: 'Huawei P30',
            maxBid: 0.01,
            budget: 250,
            status: 'paused',
            startDate: new Date('2021-01-01'),
        },
        {
            advertiserId: 2,
            name: 'Restaurants',
            brand: 'Cafe Rumano',
            maxBid: 0.03,
            budget: 350,
            status: 'active',
            startDate: new Date('2024-01-01'),
        },
        {
            advertiserId: 2,
            name: 'Restaurants',
            brand: 'Cafe Baritono',
            maxBid: 0.035,
            budget: 380,
            status: 'active',
            startDate: new Date('2024-01-01'),
        },
        {

            advertiserId: 3,
            name: 'Ninja View Campaign',
            brand: 'Ninja View',
            maxBid: 0.04,
            budget: 3000,
            status: 'active',
            startDate: new Date('2024-05-01'),
            endDate: new Date('2024-05-31'),
        },
        {
            advertiserId: 4,
            name: 'Great Story Campaign',
            brand: 'Great Story',
            maxBid: 0.05,
            budget: 400,
            status: 'active',
            startDate: new Date('2024-06-01'),
            endDate: new Date('2024-07-31'),
        },
        {
            advertiserId: 5,
            name: 'Hill St LTD Campaign',
            brand: 'Hill St LTD',
            maxBid: 0.06,
            budget: 500.45,
            status: 'active',
            startDate: new Date('2024-07-01'),
            endDate: new Date('2024-12-31'),
        },
        {
            advertiserId: 6,
            name: 'DSA Adv Campaign',
            brand: 'DSA Adv',
            status: 'active',
            maxBid: 0.07,
            budget: 600,
            startDate: new Date('2024-05-20'),
        },
        {
            advertiserId: 7,
            name: 'Others Inc Campaign',
            brand: 'Others Inc',
            maxBid: 0.07,
            budget: 700,
            status: 'paused',
            startDate: new Date('2024-04-01'),
            endDate: new Date('2024-09-31'),
        },
        {
            advertiserId: 8,
            name: 'Finally GA Campaign',
            brand: 'Finally GA',
            maxBid: 0.08,
            budget: 800,
            startDate: new Date('2021-01-01'),
            endDate: new Date('2021-12-31'),
            status: 'expired',
        },
        {
            advertiserId: 9,
            name: 'EP Inc Campaign',
            brand: 'EP Inc',
            maxBid: 0.09,
            budget: 900,
            status: 'active',
            startDate: new Date('2024-01-01'),
            endDate: new Date('2024-12-31'),
        },
        {
            advertiserId: 10,
            name: 'Kualus Campaign',
            brand: 'Kualus',
            maxBid: 0.1,
            budget: 1000,
            status: 'active',
            startDate: new Date('2024-01-01'),
            endDate: new Date('2024-12-31'),
        }
        ]
    })

    const ads = await prisma.ad.createMany({
        data: [{
            campaignId: 1,
            name: 'Iphone 15',
            targetDeviceType: 'rooftop',
            creativeFormat: 'video',
            creativeURL: 'https://www.apple.com/iphone-15/video',
            landingURL: 'https://www.apple.com/iphone-15/',
            status: 'active',
        },
        {
            campaignId: 1,
            name: 'Iphone 15 pro',
            targetDeviceType: 'rooftop',
            creativeFormat: 'video',
            creativeURL: 'https://www.apple.com/iphone-15-pro/video',
            landingURL: 'https://www.apple.com/iphone-15-pro/',
            status: 'active',
        },
        {
            campaignId: 2,
            name: 'Samsung Galaxy 20',
            targetDeviceType: 'rooftop',
            creativeFormat: 'video',
            creativeURL: 'https://www.samsumg.com/galaxy-20/video',
            landingURL: 'https://www.samsumg.com/galaxy-20/',
            status: 'active',
        },
        {
            campaignId: 2,
            name: 'Samsung Galaxy 20 pro',
            targetDeviceType: 'rooftop',
            creativeFormat: 'video',
            creativeURL: 'https://www.samsumg.com/galaxy-20-pro/video',
            landingURL: 'https://www.samsumg.com/galaxy-20-pro/',
            status: 'active',
        },
        {
            campaignId: 2,
            name: 'Samsung Galaxy 20 pro ultra',
            targetDeviceType: 'rooftop',
            creativeFormat: 'video',
            creativeURL: 'https://www.samsumg.com/galaxy-20-pro-ultra/video',
            landingURL: 'https://www.samsumg.com/galaxy-20-pro-ultra/',
            status: 'active',
        },
        {
            campaignId: 3,
            name: 'Huawei P30',
            targetDeviceType: 'rooftop',
            creativeFormat: 'video',
            creativeURL: 'https://www.huawei.com/p30/video',
            landingURL: 'https://www.huawei.com/p30/',
            status: 'active',
        },
        {
            campaignId: 3,
            name: 'Huawei P30 pro',
            targetDeviceType: 'rooftop',
            creativeFormat: 'video',
            creativeURL: 'https://www.huawei.com/p30-pro/video',
            landingURL: 'https://www.huawei.com/p30-pro/',
            status: 'active',
        },
        {
            campaignId: 4,
            name: 'Cafe Rumano',
            targetDeviceType: 'rooftop',
            creativeFormat: 'video',
            creativeURL: 'https://www.caferumano.com/video',
            landingURL: 'https://www.caferumano.com/',
            status: 'active',
        },
        {
            campaignId: 5,
            name: 'Cafe Baritono',
            targetDeviceType: 'rooftop',
            creativeFormat: 'video',
            creativeURL: 'https://www.cafebaritono.com/video',
            landingURL: 'https://www.cafebaritono.com/',
            status: 'active',
        },
        {
            campaignId: 6,
            name: 'Ninja View',
            targetDeviceType: 'rooftop',
            creativeFormat: 'video',
            creativeURL: 'https://www.ninjaview.com/video',
            landingURL: 'https://www.ninjaview.com/',
            status: 'active',
        },
        {
            campaignId: 7,
            name: 'Great Story',
            targetDeviceType: 'rooftop',
            creativeFormat: 'video',
            creativeURL: 'https://www.greatstory.com/video',
            landingURL: 'https://www.greatstory.com/',
            status: 'active',
        },
        {
            campaignId: 8,
            name: 'Hill St LTD',
            targetDeviceType: 'rooftop',
            creativeFormat: 'video',
            creativeURL: 'https://www.hillstltd.com/video',
            landingURL: 'https://www.hillstltd.com/',
            status: 'active',
        },
        {
            campaignId: 9,
            name: 'DSA Adv',
            targetDeviceType: 'rooftop',
            creativeFormat: 'video',
            creativeURL: 'https://www.dsaadv.com/video',
            landingURL: 'https://www.dsaadv.com/',
            status: 'active',
        },
        {
            campaignId: 10,
            name: 'Others Inc',
            targetDeviceType: 'rooftop',
            creativeFormat: 'video',
            creativeURL: 'https://www.othersinc.com/video',
            landingURL: 'https://www.othersinc.com/',
            status: 'active',
        },
        ]
    })

    const companies = await prisma.company.createMany({
        data: [{
            name: 'Blue Taxi Company',
            taxNumber: '1234567890',
            bank: 'Bank of America',
            bankAccount: '123456789',
            accountType: 'checking',
            contact: 'John Doe',
            email: 'blue@taxi.com',
            phone: '123-456-7890',
            address: '123 Main St, Anytown, USA',
        },
        {
            name: 'Yellow Taxi Company',
            taxNumber: '1234567891',
            bank: 'Bank of England',
            bankAccount: '123456790',
            accountType: 'checking',
            contact: 'Jane Doe',
            email: 'yellow@taxily.com',
            phone: '123-456-7891',
            address: '124 Main St, Anytown, USA',
        },
        {
            name: 'Red Taxi Company',
            taxNumber: '1234567892',
            bank: 'Bank of Canada',
            bankAccount: '123456791',
            accountType: 'saving',
            contact: 'John Smith',
            email: 'why@canada.co',
            phone: '123-456-7892',
            address: '125 Main St, Anytown, USA',
        },
    ]
    })

    const drivers = await prisma.driver.createMany({
        data:[
            {
                companyId: 1,
                vehicleId: 1,
                firstName: 'John',
                lastName: 'Doe',                
                email: 'his2@ksd.com',
                alternativeEmail: 'his2s@ksd.com',
                phone: '123-456-7890',
                alternativePhone: '123-456-7891',
                countryISO: 'GT',
                countryName: 'Guatemala',
                address: '123 Main St, Guatemala City, Guatemala',
                state: 'Guatemala',
                city: 'Guatemala City',
                department: 'Guatemala',
                municipality: 'Guatemala City',
                zone: '1',
                driversLicense: '1234567890',
                driversLicenseURL: 'https://www.guatemala.com/drivers-license',
                rideSharingCompany: 'Uber',                
            },
            {
                companyId: 1,
                vehicleId: 2,
                firstName: 'Jane',
                lastName: 'Doe',                
                email: 'jorsey@gmail.com',
                alternativeEmail: 'norj@yhahoo.com',
                phone: '123-456-7555',
                alternativePhone: '123-456-7556',
                countryISO: 'GT',
                countryName: 'Guatemala',
                address: '144 Alt St, Guatemala City, Guatemala',
                state: 'Guatemala',
                city: 'Guatemala City',
                department: 'Guatemala',
                municipality: 'Guatemala City',
                zone: '1',
                driversLicense: '1234567891',
                driversLicenseURL: 'https://www.guatemala.com/drivers-license',
                rideSharingCompany: 'Uber',                
            },{
                companyId: 1,
                vehicleId: 3,
                firstName: 'John',
                lastName: 'Smith',                
                email: 'whyno@email.com',
                alternativeEmail: 'whynoaltemail@gmaoil.com',
                phone: '123-456-7557',
                alternativePhone: '123-456-7558',
                countryISO: 'GT',
                countryName: 'Guatemala',
                address: '144 Alt St, Guatemala City, Guatemala',
                state: 'Guatemala',
                city: 'Guatemala City',
                department: 'Guatemala',
                municipality: 'Guatemala City',
                zone: '1',
                driversLicense: '1234777892',
                driversLicenseURL: 'https://www.guatemala.com/drivers-license',
                rideSharingCompany: 'Uber',                
            },
            {
                companyId: 2,
                vehicleId: 4,
                firstName: 'Arturo',
                lastName: 'Perez',
                email: 'arpe@hotma.com',
                alternativeEmail: 'pear@gma.com',
                phone: '123-456-7559',
                alternativePhone: '123-456-7560',
                countryISO: 'GT',
                countryName: 'Guatemala',
                address: '28-99 zona 10, Guatemala City, Guatemala',
                state: 'Guatemala',
                city: 'Guatemala City',
                department: 'Guatemala',
                municipality: 'Guatemala City',
                zone: '10',
                driversLicense: '1234567893',
                driversLicenseURL: 'https://www.guatemala.com/drivers-license',
                rideSharingCompany: 'InDriver',
            },
            {
                companyId: 2,
                vehicleId: 5,
                firstName: 'Maria',
                lastName: 'Garcia',
                email: 'margar@alkd.com',
                alternativeEmail: 'garmar@kkk.com',
                phone: '123-456-7561',
                alternativePhone: '123-456-7562',
                countryISO: 'GT',
                countryName: 'Guatemala',
                address: '01-07 zona 15, Guatemala City, Guatemala',
                state: 'Guatemala',
                city: 'Guatemala City',
                department: 'Guatemala',
                municipality: 'Guatemala City',
                zone: '15',
                driversLicense: '1234567894',
                driversLicenseURL: 'https://www.guatemala.com/drivers-license',
                rideSharingCompany: 'InDriver',
            },     
            {
                companyId: 3,
                vehicleId: 6,
                firstName: 'Juan',
                lastName: 'Perez',
                email: 'jape@juape.com',
                alternativeEmail: 'altja@pe.com',
                phone: '123-456-7563',
                alternativePhone: '123-456-7564',
                countryISO: 'GT',
                countryName: 'Guatemala',
                address: '01-07 zona 15, Guatemala City, Guatemala',
                state: 'Guatemala',
                city: 'Guatemala City',
                department: 'Guatemala',
                municipality: 'Guatemala City',
                zone: '15',
                driversLicense: '1234567895',
                driversLicenseURL: 'https://www.guatemala.com/drivers-license',
                rideSharingCompany: 'Uber',
            },
            {
                companyId: 3,
                vehicleId: 7,
                firstName: 'Luca',
                lastName: 'Alvarez',
                email: 'alva@res.com',
                alternativeEmail: 'res@pe.com',
                phone: '123-999-7563',
                alternativePhone: '303-456-7564',
                countryISO: 'GT',
                countryName: 'Guatemala',
                address: '01-07 zona 07, Guatemala City, Guatemala',
                state: 'Guatemala',
                city: 'Guatemala City',
                department: 'Guatemala',
                municipality: 'Guatemala City',
                zone: '07',
                driversLicense: '1234567896',
                driversLicenseURL: 'https://www.guatemala.com/drivers-license',
                rideSharingCompany: 'Uber',                
            },
            {
                companyId: 3,
                vehicleId: 8,
                firstName: 'Sara',
                lastName: 'Gomez',
                email: 'sago@lll.com',
                alternativeEmail: 'gosa@yho.com',
                phone: '123-456-7565',
                alternativePhone: '123-456-7566',
                countryISO: 'GT',
                countryName: 'Guatemala',
                address: '01-22 zona 8, Guatemala City, Guatemala',
                state: 'Guatemala',
                city: 'Guatemala City',
                department: 'Guatemala',
                municipality: 'Guatemala City',
                zone: '8',
                driversLicense: '1234567897',
                driversLicenseURL: 'https://www.guatemala.com/drivers-license',
                rideSharingCompany: 'Uber',
            },
            {
                companyId: 3,
                vehicleId: 9,
                firstName: 'Luis',
                lastName: 'Garcia',
                email: 'luga@gaga.com',
                alternativeEmail: 'pe@pon.net',
                phone: '123-456-7567',
                alternativePhone: '123-456-7568',
                countryISO: 'GT',
                countryName: 'Guatemala',
                address: '15-07 zona 11, Guatemala City, Guatemala',
                state: 'Guatemala',
                city: 'Guatemala City',
                department: 'Guatemala',
                municipality: 'Guatemala City',
                zone: '11',
                driversLicense: '1234567898',
                driversLicenseURL: 'https://www.guatemala.com/drivers-license',
                rideSharingCompany: 'Uber',
            },
            {
                companyId: 3,
                vehicleId: 10,
                firstName: 'Maria',
                lastName: 'De Leon',
                email: 'madele@on.com',
                alternativeEmail: 'oth.alt@alt.com',
                phone: '123-456-7569',
                alternativePhone: '123-456-7570',
                countryISO: 'GT',
                countryName: 'Guatemala',
                address: '11-17 zona 18, Guatemala City, Guatemala',
                state: 'Guatemala',
                city: 'Guatemala City',
                department: 'Guatemala',
                municipality: 'Guatemala City',
                zone: '18',
                driversLicense: '1234567899',
                driversLicenseURL: 'https://www.guatemala.com/drivers-license',
                rideSharingCompany: 'Uber',
            },
            {
                companyId: 3,                
                firstName: 'Alvaro',
                lastName: 'Lopez',
                email: 'allo@que.tal',
                alternativeEmail: 'yo@muy.bn',
                phone: '123-456-7571',
                alternativePhone: '123-456-7572',
                countryISO: 'GT',
                countryName: 'Guatemala',
                address: '11-17 zona 21, Guatemala City, Guatemala',
                state: 'Guatemala',
                city: 'Guatemala City',
                department: 'Guatemala',
                municipality: 'Guatemala City',
                zone: '21',
                driversLicense: '1234567800',
                driversLicenseURL: 'https://www.guatemala.com/drivers-license',
                rideSharingCompany: 'Uber',                
            }
        ]
    })


    const vehicles = await prisma.vehicle.createMany({
        data:[
            {
                companyId: 1,
                driverId: 1,
                make: 'Toyota',
                model: 'Corolla',
                type: 'sedan',
                trim: 'LE',
                color: 'white',
                year: 2021,
                licensePlate: '123-456',
                vin: '1234567890',
                numberOfSeats: 5,
            },
            {
                companyId: 1,
                driverId: 2,
                make: 'Honda',
                model: 'Civic',
                type: 'sedan',
                trim: 'LX',
                color: 'black',
                year: 2009,
                licensePlate: '123-457',
                vin: '1234567891',
                numberOfSeats: 5,
            },
            {
                companyId: 1,
                driverId: 3,                
                make: 'Ford',
                model: 'Fusion',
                type: 'suv',
                trim: 'SE',
                color: 'blue',
                year: 2020,
                licensePlate: '123-458',
                vin: '1234567892',
                numberOfSeats: 5,
            },
            {
                companyId: 2,
                driverId: 4,
                make: 'Chevrolet',
                model: 'Malibu',
                type: 'sedan',
                trim: 'LT',
                color: 'red',
                year: 2018,
                licensePlate: '123-459',
                vin: '1234567893',
                numberOfSeats: 5,
            },
            {
                companyId: 2,
                driverId: 5,
                make: 'Nissan',
                model: 'Altima',
                type: 'sedan',
                trim: 'S',
                color: 'silver',
                year: 2000,
                licensePlate: '123-460',
                vin: '1234567894',
                numberOfSeats: 5,
            },
            {
                companyId: 3,
                driverId: 6,
                make: 'Hyundai',
                model: 'Sonata',
                type: 'sedan',
                trim: 'SE',
                color: 'gray',
                year: 2015,
                licensePlate: '123-461',
                vin: '1234567895',
                numberOfSeats: 5,
            },
            {
                companyId: 1,
                driverId: 7,
                make: 'Kia',
                model: 'Sportage',
                type: 'suv',
                trim: 'LX',
                color: 'white',
                year: 2021,
                licensePlate: '123-462',
                vin: '1234567896',
                numberOfSeats: 5,
            },
            {
                companyId: 1,
                driverId: 8,
                make: 'Volkswagen',
                model: 'Passat',
                type: 'sedan',
                trim: 'S',
                color: 'black',
                year: 2021,
                licensePlate: '123-463',
                vin: '1234567897',
                numberOfSeats: 5,
            },
            {
                companyId: 1,
                driverId: 9,
                make: 'Subaru',
                model: 'Legacy',
                type: 'sedan',
                trim: 'Base',
                color: 'blue',
                year: 2017,
                licensePlate: '123-464',
                vin: '1234567898',
                numberOfSeats: 5,
            },
            {
                companyId: 1,
                driverId: 10,
                make: 'Isuzu',
                model: 'DMax',
                type: 'pickup',
                trim: 'Sport',
                color: 'red',
                year: 2015,
                licensePlate: '123-465',
                vin: '1234567899',
                numberOfSeats: 5,
            },
        ]
    })    

    const devices = await prisma.device.createMany({
        data:[
            {
                type: 'rooftop',
                make: 'byd',
                model: 'model 1',
                screenWidth: 1080,
                screenHeight: 460,
                resolution: '1080x460',
                os: 'ubuntu',
                osVersion: '20.04',
                serialNumber: '1234567890',
                vehicleId: 1,
            },
            {
                type: 'tablet',
                make: 'HuaWei',
                model: 'Mate Pad',
                screenWidth: 2560,
                screenHeight: 1440,
                resolution: '2560x1440',
                os: 'android',
                osVersion: '11',
                serialNumber: '1234567330',
                vehicleId: 1,
            },
            {
                type: 'tablet',
                make: 'Samsung',
                model: 'Galaxy Tab',
                screenWidth: 1920,
                screenHeight: 1080,
                resolution: '1920x1080',
                os: 'android',
                osVersion: '10',
                serialNumber: '1234567331',
                vehicleId: 2,
            },
            {
                type: 'rooftop',
                make: 'byd',
                model: 'model 2',
                screenWidth: 1080,
                screenHeight: 460,
                resolution: '1080x460',
                os: 'ubuntu',
                osVersion: '20.04',
                serialNumber: '1223567891',
                vehicleId: 3,
            },
            {
                type: 'rooftop',
                make: 'byd',
                model: 'model 3',
                screenWidth: 1080,
                screenHeight: 460,
                resolution: '1080x460',
                os: 'ubuntu',
                osVersion: '20.04',
                serialNumber: 'AAEFSDF23121',
                vehicleId: 4,
            },
            {
                type: 'rooftop',
                make: 'byd',
                model: 'model 3',
                screenWidth: 1080,
                screenHeight: 460,
                resolution: '1080x460',
                os: 'ubuntu',
                osVersion: '20.04',
                serialNumber: 'AAEFSDF23122',
                vehicleId: 5,
            },
            {
                type: 'rooftop',
                make: 'byd',
                model: 'model 3',
                screenWidth: 1080,
                screenHeight: 460,
                resolution: '1080x460',
                os: 'ubuntu',
                osVersion: '20.04',
                serialNumber: 'AAEFSDF23123',
                vehicleId: 6,
            },
            {
                type: 'rooftop',
                make: 'byd',
                model: 'model 3',
                screenWidth: 1080,
                screenHeight: 460,
                resolution: '1080x460',
                os: 'ubuntu',
                osVersion: '20.04',
                serialNumber: 'AAEFSDF99989',
                vehicleId: 7,
            },
            {
                type: 'rooftop',
                make: 'byd',
                model: 'model 3',
                screenWidth: 1080,
                screenHeight: 460,
                resolution: '1080x460',
                os: 'ubuntu',
                osVersion: '20.04',
                serialNumber: 'AAEFSDF99990',
                vehicleId: 8,
            },
            {
                type: 'rooftop',
                make: 'byd',
                model: 'model 8',
                screenWidth: 1080,
                screenHeight: 460,
                resolution: '1080x460',
                os: 'ubuntu',
                osVersion: '20.04',
                serialNumber: 'AAEFSDF99991',
                vehicleId: 9,
            }
        ]
    })    

    const locations = await prisma.location.createMany({
        data:[
            {
                type:'walkway',
                name: 'Roosevelt Walkway',
                address: 'Roosevelt Ave, Zona 11 , GT',
                city: 'Guatemala City',
                state: 'Guatemala',
                country: 'Guatemala',
                postalCode: '01011',
                description: 'Roosevelt Walkway is a popular walkway in the city',
                latitude: 14.5895,
                longitude: -90.5518,
            },
            {
                type:'walkway',
                name: 'La Reforma Walkway',
                address: 'Reforma Ave, Zona 9 , GT',
                city: 'Guatemala City',
                state: 'Guatemala',
                country: 'Guatemala',
                postalCode: '01009',
                description: 'La Reforma Walkway is a popular walkway in the city',
                latitude: 14.5895,
                longitude: -90.5518,
            },
            {
                type:'billboard',
                name: 'Galavista Las Americas',
                address: 'Las Americas Ave, Zona 14 , GT',
                city: 'Guatemala City',
                state: 'Guatemala',
                country: 'Guatemala',
                postalCode: '01014',
                description: 'Las Americas Galavista is a popular mall in the city',
                latitude: 14.5895,
                longitude: -90.5518,
            },
            {
                type:'bus stop',
                name: 'La Reforma Bus Stop',
                address: 'Reforma Ave, Zona 9 , GT',
                city: 'Guatemala City',
                state: 'Guatemala',
                country: 'Guatemala',
                postalCode: '01009',
                description: 'La Reforma bus stop is a popular site in the city',
                latitude: 14.5895,
                longitude: -90.5518,
            },
            {
                type:'bus stop',
                name: 'Roosevelt Bus Stop',
                address: 'Roosevelt Ave, Zona 11 , GT',
                city: 'Guatemala City',
                state: 'Guatemala',
                country: 'Guatemala',
                postalCode: '01011',
                description: 'Roosevelt bus stop is a popular site in the city',
                latitude: 14.5895,
                longitude: -90.5518,
            },
            {
                type:'bus stop',
                name: 'Las Americas Bus Stop',
                address: 'Las Americas Ave, Zona 14 , GT',
                city: 'Guatemala City',
                state: 'Guatemala',
                country: 'Guatemala',
                postalCode: '01014',
                description: 'Las Americas bus stop is a popular site in the city',
                latitude: 14.5895,
                longitude: -90.5518,
            },
            {
                type:'bus stop',
                name: 'La Reforma Bus Stop',
                address: 'Reforma Ave, Zona 9 , GT',
                city: 'Guatemala City',
                state: 'Guatemala',
                country: 'Guatemala',
                postalCode: '01009',
                description: 'La Reforma bus stop is a popular site in the city',
                latitude: 14.5895,
                longitude: -90.5518,
            },
            {
                type:'bus stop',
                name: 'Roosevelt Bus Stop',
                address: 'Roosevelt Ave, Zona 11 , GT',
                city: 'Guatemala City',
                state: 'Guatemala',
                country: 'Guatemala',
                postalCode: '01011',
                description: 'Roosevelt bus stop is a popular site in the city',
                latitude: 14.5895,
                longitude: -90.5518,
            },
            {
                type:'bus stop',
                name: 'Las Americas Bus Stop',
                address: 'Las Americas Ave, Zona 14 , GT',
                city: 'Guatemala City',
                state: 'Guatemala',
                country: 'Guatemala',
                postalCode: '01014',
                description: 'Las Americas bus stop is a popular site in the city',
                latitude: 14.5895,
                longitude: -90.5518,
            },
        ]
    })

    console.log(`Advertisers Seed -> ${JSON.stringify(advertisers)}`)
    console.log(`Campaigns Seed -> ${JSON.stringify(campaigns)}`)
    console.log(`Ads Seed -> ${JSON.stringify(ads)}`)
    console.log(`Company Seed -> ${JSON.stringify(companies)}`)
    console.log(`Vehicles Seed -> ${JSON.stringify(vehicles)}`)    
    console.log(`Drivers Seed -> ${JSON.stringify(drivers)}`)  
    console.log(`Location Seed -> ${JSON.stringify(locations)}`)  
    console.log(`Devices Seed -> ${JSON.stringify(devices)}`)
}

main()
    .then(async () => {
        await prisma.$disconnect()
    })
    .catch(async (e) => {
        console.error(e)
        await prisma.$disconnect()
        process.exit(1)
    })
