version: '3.8'

services:
  adrush-api:
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - "3000:3000"
    container_name: 
      adrush-api    
    command: ["npm","run","start:dev"]    
    volumes:
      - ./src:/app/src
    depends_on:
      - adrush-db   

  adrush-db:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: 
      adrush-db
    volumes:
      - postgres:/var/lib/postgresql/data

  adrush-df:
    image: chainguard/dragonfly:latest
    ports:
      - "6379"
    container_name:
      adrush-df
    volumes:
      - dragonfly:/var/lib/dragonfly/data    

volumes:
    postgres:
    dragonfly:    
    

